name: others

on: [pull_request]

jobs:
  behave:
    runs-on: ${{ matrix.os }}
    env:
      DCS: ${{ matrix.dcs }}
      ETCDVERSION: 3.3.13
      PGVERSION: 13.0-beta2  # for windows and macos
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        dcs: [etcd,etcd3,raft]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python .github/workflows/install_deps.py
      if: matrix.os != 'windows-latest' || matrix.dcs == 'etcd3'
    - name: Run behave tests
      run: |
        python .github/workflows/run_tests.py
      if: matrix.os != 'windows-latest' || matrix.dcs == 'etcd3'
