name: ubuntu

on: [pull_request]

jobs:
  behave:
    runs-on: ubuntu-latest
    env:
      DCS: ${{ matrix.dcs }}
      ETCDVERSION: 3.3.13
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.5, 3.8]
        dcs: [etcd, etcd3, consul, exhibitor, kubernetes, raft]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python .github/workflows/install_deps.py
    - name: Run behave tests
      run: |
        python .github/workflows/run_tests.py
    - name: Upload Coverage
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: unit-${{ matrix.os }}-python-2.7
        COVERALLS_PARALLEL: true
      run: |
        coveralls debug


  finish:
    name: Finish Coveralls
    needs: behave
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls debug --finish
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
