name: ubuntu

on: [pull_request]

jobs:
  behave:
    runs-on: ubuntu-latest
    env:
      DCS: ${{ matrix.dcs }}
      ETCDVERSION: 3.3.13
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.5, 3.8]
        dcs: [etcd, etcd3, consul, exhibitor, kubernetes, raft]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python .github/workflows/install_deps.py
    - name: Run behave tests
      run: |
        python .github/workflows/run_tests.py
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: behave-ubuntu-latest-${{ matrix.dcs }}-python-${{ matrix.python-version }}
        parallel: true


  finish:
    needs: behave
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
