name: others

on: [pull_request]

jobs:
  behave:
    runs-on: ${{ matrix.os }}
    env:
      DCS: ${{ matrix.dcs }}
      ETCDVERSION: 3.3.13
      PGVERSION: 12.1-1  # for windows and macos
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]  #, windows-latest]
        dcs: [etcd,etcd3,raft]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python .github/workflows/install_deps.py
    - name: Run behave tests
      run: |
        python .github/workflows/run_tests.py
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: behave-${{ matrix.os }}-${{ matrix.dcs }}-python-3.7
        parallel: true


  finish:
    needs: behave
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
