name: ubuntu

on: [pull_request]

jobs:
  behave:
    runs-on: ubuntu-latest
    env:
      DCS: ${{ matrix.dcs }}
      ETCDVERSION: 3.3.13
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.5]
#        python-version: [2.7, 3.5, 3.8]
#        dcs: [etcd, consul, exhibitor, kubernetes]
        dcs: [kubernetes]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python .github/workflows/install_deps.py
    - name: Run behave tests
      run: |
        python .github/workflows/run_tests.py
