name: unit

on: [pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
      if: matrix.os != 'windows-latest'
    - name: Install dependencies
      run: |
        python .github/workflows/install_deps.py
      if: matrix.os != 'windows-latest'
    - name: Run tests and flake8
      run: |
        python .github/workflows/run_tests.py
      if: matrix.os != 'windows-latest'

    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
      if: matrix.os != 'windows-latest'
    - name: Install dependencies
      run: |
        python .github/workflows/install_deps.py
      if: matrix.os != 'windows-latest'
    - name: Run tests and flake8
      run: |
        python .github/workflows/run_tests.py
      if: matrix.os != 'windows-latest'

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python .github/workflows/install_deps.py
    - name: Run tests and flake8
      run: |
        python .github/workflows/run_tests.py

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python .github/workflows/install_deps.py
    - name: Run tests and flake8
      run: |
        python .github/workflows/run_tests.py

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python .github/workflows/install_deps.py
    - name: Run tests and flake8
      run: |
        python .github/workflows/run_tests.py
