name: unit

on: [pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
      if: matrix.os != 'windows-latest'
    - name: Install dependencies
      run: |
        python .github/workflows/install_deps.py
      if: matrix.os != 'windows-latest'
    - name: Run tests and flake8
      run: |
        python .github/workflows/run_tests.py
      if: matrix.os != 'windows-latest'
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: unit-${{ matrix.os }}-python-2.7
        parallel: true

    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Install dependencies
      run: |
        python .github/workflows/install_deps.py
    - name: Run tests and flake8
      run: |
        python .github/workflows/run_tests.py
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: unit-${{ matrix.os }}-python-3.5
        parallel: true

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python .github/workflows/install_deps.py
    - name: Run tests and flake8
      run: |
        python .github/workflows/run_tests.py
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: unit-${{ matrix.os }}-python-3.6
        parallel: true

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python .github/workflows/install_deps.py
    - name: Run tests and flake8
      run: |
        python .github/workflows/run_tests.py
    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: unit-${{ matrix.os }}-python-3.7
        parallel: true

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python .github/workflows/install_deps.py
    - name: Run tests and flake8
      run: |
        python .github/workflows/run_tests.py

    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: unit-${{ matrix.os }}-python-3.8
        parallel: true


  finish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
