name: Patroni unit tests

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        #        exclude:
        #        - os: windows-latest
        #          python-version: 2.7
        #        - os: macos-latest
        #          python-version: 2.7

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 2.7
      uses: &setup actions/setup-python@v1
      with:
        python-version: 2.7
    - &deps
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install psycopg2-binary behave codacy-coverage coverage coveralls flake8 mock pytest-cov pytest setuptools
    - &flake8
      name: Lint with flake8
      run: |
        python setup.py flake8
    - name: &pytest Test with pytest
      run: |
        python setup.py test

    - name: Set up Python 3.5
      uses: *setup
      with:
        python-version: 3.5
    - *deps
    - *flake8
    - *pytest

    - name: Set up Python 3.6
      uses: *setup
      with:
        python-version: 3.6
    - *deps
    - *flake8
    - *pytest

    - name: Set up Python 3.7
      uses: *setup
      with:
        python-version: 3.7
    - *deps
    - *flake8
    - *pytest

    - name: Set up Python 3.8
      uses: *setup
      with:
        python-version: 3.8
    - *deps
    - *flake8
    - *pytest
